spring:
  application:
    name: ms-historico

  datasource:
    # url: jdbc:mysql://localhost:3306/medtech_historico
    url: jdbc:mysql://mysql:3306/medtech
    username: root
    password: root
    driver-class-name: com.mysql.cj.jdbc.Driver

  jpa:
    hibernate:
      ddl-auto: update
    show-sql: true
    properties:
      hibernate:
        dialect: org.hibernate.dialect.MySQLDialect

  rabbitmq:
    # host: localhost
    host: rabbitmq
    port: 5672
    username: guest
    password: guest

  graphql:
    graphiql:
      enabled: true
      path: /graphiql
    path: /graphql

server:
  port: 8081
